-- DL Modas: schema base aprovado (MySQL 8+ / InnoDB / utf8mb4).
-- Use apenas em banco novo; não execute sobre uma base existente.
CREATE TABLE usuarios (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100), email VARCHAR(100) UNIQUE, senha VARCHAR(255), tipo ENUM('cliente','admin') DEFAULT 'cliente', ativo TINYINT(1) DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, codigo_confirmacao VARCHAR(10), token_confirmacao VARCHAR(255), token_redefinicao VARCHAR(64), token_redefinicao_expira_em DATETIME, celular VARCHAR(20), rua VARCHAR(150), numero VARCHAR(20), bairro VARCHAR(100), cidade VARCHAR(100), estado VARCHAR(50), cep VARCHAR(10), foto VARCHAR(255), INDEX idx_usuarios_token_redefinicao(token_redefinicao)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE categorias (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE produtos (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255) NOT NULL, descricao TEXT, preco_base DECIMAL(10,2) NOT NULL, ativo TINYINT(1) DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, categoria_id INT, CONSTRAINT chk_preco_base_nonnegative CHECK(preco_base >= 0), CONSTRAINT produtos_ibfk_1 FOREIGN KEY(categoria_id) REFERENCES categorias(id), INDEX idx_produtos_categoria_ativo(categoria_id, ativo)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE produto_variacoes (id INT AUTO_INCREMENT PRIMARY KEY, produto_id INT NOT NULL, cor VARCHAR(50), tamanho VARCHAR(50), preco DECIMAL(10,2) NOT NULL, estoque INT NOT NULL DEFAULT 0, ativo TINYINT(1) NOT NULL DEFAULT 1, sku VARCHAR(100), CONSTRAINT chk_estoque_nonnegative CHECK(estoque >= 0), CONSTRAINT chk_preco_variacao_nonnegative CHECK(preco >= 0), CONSTRAINT produto_variacoes_ibfk_1 FOREIGN KEY(produto_id) REFERENCES produtos(id) ON DELETE CASCADE, INDEX idx_produto_variacoes_produto_id(produto_id), INDEX idx_produto_variacoes_produto_ativo(produto_id, ativo)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE produto_imagens (id INT AUTO_INCREMENT PRIMARY KEY, produto_id INT NOT NULL, url TEXT NOT NULL, ordem INT DEFAULT 0, is_principal TINYINT(1) DEFAULT 0, CONSTRAINT produto_imagens_ibfk_1 FOREIGN KEY(produto_id) REFERENCES produtos(id) ON DELETE CASCADE, INDEX idx_produto_imagens_produto_principal(produto_id, is_principal)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE produto_imagens_backup (id INT, produto_id INT, url TEXT, ordem INT DEFAULT 0, is_principal TINYINT(1) DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pedidos (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, status ENUM('','pendente','aguardando_confirmacao','pago','enviado','entregue','cancelado','expirado') DEFAULT NULL, total DECIMAL(10,2) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, pagamento VARCHAR(50) DEFAULT 'pendente', comprovante VARCHAR(255), expires_at DATETIME, pix_key VARCHAR(255), CONSTRAINT chk_total_nonnegative CHECK(total >= 0), CONSTRAINT pedidos_ibfk_1 FOREIGN KEY(usuario_id) REFERENCES usuarios(id), INDEX idx_pedidos_status_created_at(status, created_at), INDEX idx_pedidos_usuario_status(usuario_id, status), INDEX idx_pedidos_status_expires_at(status, expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pedido_itens (id INT AUTO_INCREMENT PRIMARY KEY, pedido_id INT NOT NULL, produto_id INT NOT NULL, variacao_id INT, quantidade INT NOT NULL, preco DECIMAL(10,2) NOT NULL, CONSTRAINT chk_quantidade_positive CHECK(quantidade > 0), CONSTRAINT chk_preco_item_nonnegative CHECK(preco >= 0), CONSTRAINT pedido_itens_ibfk_1 FOREIGN KEY(pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE, CONSTRAINT pedido_itens_ibfk_2 FOREIGN KEY(produto_id) REFERENCES produtos(id), CONSTRAINT pedido_itens_ibfk_3 FOREIGN KEY(variacao_id) REFERENCES produto_variacoes(id), INDEX idx_pedido_itens_pedido_id(pedido_id), INDEX idx_pedido_itens_produto_id(produto_id), INDEX variacao_id(variacao_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE favoritos (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, produto_id INT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY unique_favorito(usuario_id, produto_id), CONSTRAINT favoritos_ibfk_1 FOREIGN KEY(usuario_id) REFERENCES usuarios(id), CONSTRAINT favoritos_ibfk_2 FOREIGN KEY(produto_id) REFERENCES produtos(id), INDEX produto_id(produto_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE carrinho (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT, produto_id INT, variacao_id INT, quantidade INT DEFAULT 1, CONSTRAINT carrinho_ibfk_1 FOREIGN KEY(usuario_id) REFERENCES usuarios(id), CONSTRAINT carrinho_ibfk_2 FOREIGN KEY(produto_id) REFERENCES produtos(id), CONSTRAINT carrinho_ibfk_3 FOREIGN KEY(variacao_id) REFERENCES produto_variacoes(id), INDEX usuario_id(usuario_id), INDEX produto_id(produto_id), INDEX variacao_id(variacao_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
